[package]
name = "stm32h7-update-server"
version = "0.1.0"
edition = "2018"

[dependencies]
userlib = {path = "../../sys/userlib", features = ["panic-messages"]}
stm32h7 = { version = "0.14", features = ["stm32h753"] }
drv-update-api = { path = "../update-api/" }
ringbuf = {path = "../../lib/ringbuf"}
idol-runtime = {git = "https://github.com/oxidecomputer/idolatry.git"}
num-traits = { version = "0.2.12", default-features = false }
zerocopy = "0.6.1"

[build-dependencies]
idol = {git = "https://github.com/oxidecomputer/idolatry.git"}

[lib]
name = "stm32h7_update_server"
crate_type = ["staticlib"]
test = false
bench = false
