[package]
name = "drv-lpc55-usart"
version = "0.1.0"
edition = "2018"

[dependencies]
userlib = {path = "../../sys/userlib", features = ["panic-messages"]}
zerocopy = "0.6.1"
lpc55-pac = "0.3.0"
drv-lpc55-gpio-api = {path = "../lpc55-gpio-api"}
drv-lpc55-syscon-api = {path = "../lpc55-syscon-api"}

[lib]
test = false
bench = false
crate_type = ["staticlib"]
