[package]
name = "drv-lpc55-usart"
version = "0.1.0"
edition = "2018"

[dependencies]
userlib = {path = "../../sys/userlib", features = ["panic-messages"]}
zerocopy = "0.6.1"
lpc55-pac = "0.3.0"
drv-lpc55-gpio-api = {path = "../lpc55-gpio-api"}
drv-lpc55-syscon-api = {path = "../lpc55-syscon-api"}


[build-dependencies]
build-util = {path = "../../build/util"}
build-lpc55pins = {path = "../../build/lpc55pins"}
serde = "1"
anyhow = "1.0.31"

[lib]
crate_type = ["staticlib"]
test = false
bench = false
