[package]
name = "task-jefe"
version = "0.1.0"
edition = "2018"

[dependencies]
abi = {path = "../../sys/abi"}
userlib = {path = "../../sys/userlib"}
hubris-num-tasks = {path = "../../sys/num-tasks", features = ["task-enum"]}
ringbuf = {path = "../../lib/ringbuf" }
num-traits = { version = "0.2.12", default-features = false }
zerocopy = "0.6.1"
cortex-m = { version = "0.7", features = ["inline-asm"] }
cortex-m-semihosting = { version = "0.3.7", features = ["inline-asm"], optional = true }
armv6m-atomic-hack = {path = "../../lib/armv6m-atomic-hack"}
task-jefe-api = {path = "../jefe-api"}
idol-runtime = {git = "https://github.com/oxidecomputer/idolatry.git"}

[build-dependencies]
build-util = {path = "../../build/util"}
idol = {git = "https://github.com/oxidecomputer/idolatry.git"}
serde = "1"

[features]
itm = [ "userlib/log-itm" ]
semihosting = [ "userlib/log-semihosting", "cortex-m-semihosting" ]
log-null = ["userlib/log-null"]

# This section is here to discourage RLS/rust-analyzer from doing test builds,
# since test builds don't work for cross compilation.
[[bin]]
name = "task-jefe"
test = false
bench = false
