name = "lpc55xpresso"
target = "thumbv8m.main-none-eabihf"
board = "lpcxpresso55s69"
chip = "../../chips/lpc55.toml"
stacksize = 1024
secure-separation = true

[kernel]
name = "lpc55xpresso"
requires = {flash = 32768, ram = 4096}
features = ["itm"]

[supervisor]
notification = 1

[outputs.bootloader_sram]
address = 0x14000000
size = 0x8000

[outputs.bootloader_flash]
address = 0x00000000
size = 0x8000

[outputs.bootloader_ram]
address = 0x20000000
size = 0x4000

# We reserve the last sector (0x8000) for flash testing
[outputs.flash]
address = 0x00008000
size = 0x88000
read = true
execute = true

[outputs.ram]
address = 0x20004000
size = 0x18000
read = true
write = true
execute = true

[signing.combined]
method = "ecc"
priv-key = "../../support/fake_certs/p256-private-key.der"

[signing.bootloader]
method = "rsa"
priv-key = "../../support/fake_certs/fake_private_key.pem"
root-cert = "../../support/fake_certs/fake_certificate.der.crt"

[bootloader]
name = "stage0"
sections = {"flash_hypo" = "flash"}
sharedsyms = ["write_to_flash"]
# Currently we have the first 0x8000 of flash and first 0x4000 of RAM
# dedicated for the stage0 bootloader and the rest for Hubris. Once we have
# multiple images this will need to be adjusted
imagea-flash-start = 0x8000
imagea-flash-size = 0x88000
imagea-ram-start = 0x20004000
imagea-ram-size = 0x18000
features = ["tz_support", "0A-hardware"]

[tasks.jefe]
name = "task-jefe"
priority = 0
start = true
features = ["itm"]
stacksize = 1536

[tasks.hiffy]
name = "task-hiffy"
priority = 3
features = ["lpc55", "gpio"]
stacksize = 2048
start = true
task-slots = ["gpio_driver"]

[tasks.idle]
name = "task-idle"
priority = 5
stacksize = 256
start = true

[tasks.syscon_driver]
name = "drv-lpc55-syscon"
priority = 2
uses = ["syscon", "anactrl", "pmc"]
start = true
stacksize = 1000

[tasks.gpio_driver]
name = "drv-lpc55-gpio"
priority = 2
uses = ["gpio", "iocon"]
start = true
stacksize = 1000
task-slots = ["syscon_driver"]

[tasks.user_leds]
name = "drv-user-leds"
features = ["lpc55"]
priority = 2
start = true
stacksize = 1000
task-slots = ["gpio_driver"]

[tasks.usart_driver]
name = "drv-lpc55-usart"
priority = 2
uses = ["flexcomm0"]
start = true
interrupts = {"flexcomm0.irq" = 1}
stacksize = 1000
task-slots = ["gpio_driver", "syscon_driver"]

[tasks.i2c_driver]
name = "drv-lpc55-i2c"
priority = 2
uses = ["flexcomm4"]
start = true
stacksize = 1000
task-slots = ["gpio_driver", "syscon_driver"]

[tasks.rng_driver]
name = "drv-lpc55-rng"
priority = 2
uses = ["rng", "pmc"]
start = true
stacksize = 1000
task-slots = ["syscon_driver"]

[tasks.spi_driver]
name = "drv-lpc55-spi-server"
priority = 2
uses = ["flexcomm8"]
start = true
interrupts = {"flexcomm8.hs_spi" = 1}
stacksize = 1000
task-slots = ["gpio_driver", "syscon_driver"]

[tasks.ping]
name = "task-ping"
features = ["uart"]
priority = 4
start = true
stacksize = 512
task-slots = [{peer = "pong"}, "usart_driver"]

[tasks.pong]
name = "task-pong"
priority = 3
start = true
stacksize = 1000
task-slots = ["user_leds"]
