[package]
name = "drv-lpc55-spi-server"
version = "0.1.0"
edition = "2018"

[dependencies]
userlib = {path = "../../sys/userlib", features = ["panic-messages"]}
zerocopy = "0.6.1"
lpc55-pac = "0.3.0"
drv-lpc55-syscon-api = {path = "../lpc55-syscon-api"}
drv-lpc55-spi = {path = "../lpc55-spi"}
drv-spi-msg = {path = "../spi-msg"}
num-traits = { version = "0.2.12", default-features = false }
drv-lpc55-gpio-api = {path = "../lpc55-gpio-api"}
ringbuf = {path = "../../lib/ringbuf"}
sprockets-rot = {path = "../../../sprockets/rot", default-features = false}
sprockets-common = {path = "../../../sprockets/common"}
hubpack = { rev = "df08cc3a6e1f97381cd0472ae348e310f0119e25", git = "https://github.com/cbiffle/hubpack.git"}
salty = "0.2.0"


[build-dependencies]
build-util = {path = "../../build/util"}
build-lpc55pins = {path = "../../build/lpc55pins"}
serde = "1"

[features]
spi0 = []

# This section is here to discourage RLS/rust-analyzer from doing test builds,
# since test builds don't work for cross compilation.
[[bin]]
name = "drv-lpc55-spi-server"
test = false
bench = false
