[package]
name = "drv-lpc55-spi-server"
version = "0.1.0"
edition = "2018"

[dependencies]
userlib = {path = "../../sys/userlib", features = ["panic-messages"]}
zerocopy = "0.6.1"
lpc55-pac = "0.3.0"
drv-lpc55-syscon-api = {path = "../lpc55-syscon-api"}
drv-lpc55-spi = {path = "../lpc55-spi"}
num-traits = { version = "0.2.12", default-features = false }
drv-lpc55-gpio-api = {path = "../lpc55-gpio-api"}
ringbuf = {path = "../../lib/ringbuf"}

[features]
spi0 = []

[lib]
test = false
bench = false
crate_type = ["staticlib"]
