name = "demo-stm32g031-nucleo"
target = "thumbv6m-none-eabi"
chip = "../../chips/stm32g0.toml"
board = "stm32g031"

[kernel]
name = "demo-stm32g0-nucleo"
requires = {flash = 11928, ram = 1992}
features = ["g031", "panic-halt"]
stacksize = 640

[supervisor]
notification = 1

[outputs.flash]
address = 0x08000000
size = 65536
read = true
execute = true

[outputs.ram]
address = 0x20000000
size = 8192
read = true
write = true
execute = false  # let's assume XN until proven otherwise

[tasks.jefe]
name = "task-jefe"
priority = 0
start = true
features = ["log-null"]
stacksize = 368

[tasks.sys]
name = "drv-stm32xx-sys"
priority = 1
uses = ["rcc", "gpio"]
start = true
features = ["g031"]
stacksize = 256

[tasks.pong]
name = "task-pong"
priority = 4
start = true
task-slots = ["user_leds"]
stacksize = 256

[tasks.user_leds]
name = "drv-user-leds"
features = ["stm32g0"]
priority = 3
start = true
task-slots = ["sys"]
stacksize = 256

[tasks.hiffy]
name = "task-hiffy"
priority = 4
start = true
task-slots = ["sys"]
stacksize = 912
features = ["stm32g0", "gpio", "micro"]

[tasks.idle]
name = "task-idle"
priority = 5
stacksize = 64
start = true
