[package]
name = "task-template"
version = "0.1.0"
edition = "2018"

[dependencies]
userlib = {path = "../../sys/userlib", features = ["panic-messages"]}

[lib]
crate_type = ["staticlib"]
test = false
bench = false
