[package]
name = "drv-lpc55-syscon"
version = "0.1.0"
edition = "2018"

[dependencies]
userlib = {path = "../../sys/userlib", features = ["panic-messages"]}
zerocopy = "0.6.1"
lpc55-pac = "0.3.0"
cortex-m = {version = "0.7", features = ["inline-asm"]}
num-traits = { version = "0.2.12", default-features = false }

[lib]
test = false
bench = false
crate_type = ["staticlib"]
