[package]
name = "drv-lpc55-rng"
version = "0.1.0"
edition = "2021"

[dependencies]
userlib = {path = "../../sys/userlib", features = ["panic-messages"]}
zerocopy = "0.6.1"
lpc55-pac = "0.3.0"
num-traits = { version = "0.2.12", default-features = false }
cfg-if = "1"
drv-lpc55-syscon-api = {path = "../lpc55-syscon-api"}
drv-rng-api = { path = "../rng-api" }
rand_chacha = { version = "0.3", default-features = false }
rand_core = { version = "0.6" }
idol-runtime = { git = "https://github.com/oxidecomputer/idolatry.git" }

[build-dependencies]
idol = { git = "https://github.com/oxidecomputer/idolatry.git" }

[lib]
name = "drv_lpc55_rng"
crate_type = ["staticlib"]
test = false
bench = false
