[package]
name = "task-idle"
version = "0.1.0"
edition = "2018"

[dependencies]
# The idle task cannot panic, so we deliberately don't request panic-messages
# to keep the binary tiny.
userlib = {path = "../../sys/userlib"}
cortex-m = { version = "0.7", features = ["inline-asm"] }

[lib]
crate_type = ["staticlib"]
test = false
bench = false
