[package]
name = "drv-stm32fx-usart"
version = "0.1.0"
edition = "2018"

[dependencies]
userlib = {path = "../../sys/userlib", features = ["panic-messages"]}
stm32f3 = { version = "0.13.2", features = ["stm32f303"], optional = true }
stm32f4 = { version = "0.13.0", features = ["stm32f407"], optional = true }
zerocopy = "0.6.1"
num-traits = { version = "0.2.12", default-features = false }

[lib]
test = false
bench = false
crate_type = ["staticlib"]
