[package]
name = "drv-stm32fx-rcc"
version = "0.1.0"
edition = "2018"

[dependencies]
userlib = {path = "../../sys/userlib", features = ["panic-messages"]}
stm32f3 = { version = "0.13.0", optional = true, default-features = false }
stm32f4 = { version = "0.13.0", optional = true, default-features = false }
zerocopy = "0.6.1"
num-traits = { version = "0.2.12", default-features = false }

[features]
f3 = ["stm32f3/stm32f303"]
f4 = ["stm32f4/stm32f407"]

[lib]
name = "drv_stm32fx_rcc"
crate_type = ["staticlib"]
test = false
bench = false
