[package]
name = "drv-spi-msg"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive-idol-err = {path = "../../lib/derive-idol-err" }
userlib = {path = "../../sys/userlib"}
num-traits = { version = "0.2.12", default-features = false }
zerocopy = "0.6.1"
ringbuf = {path = "../../lib/ringbuf"}
sprockets-common = {path = "../../../sprockets/common"}
hubpack = { rev = "df08cc3a6e1f97381cd0472ae348e310f0119e25", git = "https://github.com/cbiffle/hubpack.git"}

[build-dependencies]
idol = {git = "https://github.com/oxidecomputer/idolatry.git"}
