[package]
name = "task-udpbroadcast"
version = "0.1.0"
edition = "2021"

[features]
vlan = ["task-net-api/vlan"]

[dependencies]
userlib = {path = "../../sys/userlib", features = ["panic-messages"]}
serde = {version = "1", default-features = false, features = ["derive"]}
ssmarshal = {version = "1", default-features = false}
num-traits = {version = "0.2", default-features = false}
task-net-api = {path = "../net-api"}

[lib]
crate_type = ["staticlib"]
test = false
bench = false
