name = "gemini-bu-rot"
target = "thumbv8m.main-none-eabihf"
board = "gemini-bu-rot-1"
chip = "../../chips/lpc55.toml"
stacksize = 1024

[kernel]
name = "gemini-bu-rot"
requires = {flash = 21504, ram = 4096}
features = ["itm"]

[signing.combined]
method = "ecc"
priv-key = "../../support/fake_certs/p256-private-key.der"

[signing.bootloader]
method = "rsa"
priv-key = "../../support/fake_certs/fake_private_key.pem"
root-cert = "../../support/fake_certs/fake_certificate.der.crt"

[bootloader]
name = "stage0"
sections = {"flash_hypo" = "flash"}
sharedsyms = ["write_to_flash"]
# Currently we have the first 0x8000 of flash and first 0x4000 of RAM
# dedicated for the stage0 bootloader and the rest for Hubris. Once we have
# multiple images this will need to be adjusted
imagea-flash-start = 0x8000
imagea-flash-size = 0x95800
imagea-ram-start = 0x20004000
imagea-ram-size = 0x3c000

[supervisor]
notification = 1

[outputs.bootloader_sram]
address = 0x14000000
size = 0x8000

[outputs.bootloader_flash]
address = 0x00000000
size = 0x8000

[outputs.bootloader_ram]
address = 0x20000000
size = 0x4000

[outputs.flash]
address = 0x00008000
size = 0x78000
read = true
execute = true

[outputs.ram]
address = 0x20004000
size = 0x3C000
read = true
write = true
execute = true

[tasks.jefe]
name = "task-jefe"
priority = 0
start = true
features = ["itm"]
stacksize = 1536

[tasks.idle]
name = "task-idle"
priority = 5
stacksize = 256
start = true

[tasks.syscon_driver]
name = "drv-lpc55-syscon"
priority = 2
uses = ["syscon", "anactrl", "pmc"]
start = true

[tasks.gpio_driver]
name = "drv-lpc55-gpio"
priority = 2
uses = ["gpio", "iocon"]
start = true
task-slots = ["syscon_driver"]

[tasks.user_leds]
name = "drv-user-leds"
features = ["lpc55"]
priority = 2
start = true
task-slots = ["gpio_driver"]

[tasks.usart_driver]
name = "drv-lpc55-usart"
priority = 2
uses = ["flexcomm0"]
start = true
interrupts = {"flexcomm0.irq" = 1}
task-slots = ["gpio_driver", "syscon_driver"]

[tasks.rng_driver]
name = "drv-lpc55-rng"
priority = 2
uses = ["rng", "pmc"]
start = true
task-slots = ["syscon_driver"]

[tasks.spi0_driver]
name = "drv-lpc55-spi-server"
priority = 2
features = ["spi0"]
uses = ["flexcomm3", "flexcomm8"]
start = true
interrupts = {"flexcomm8.hs_spi" = 1}
stacksize = 1000
task-slots = ["gpio_driver", "syscon_driver"]

[tasks.ping]
name = "task-ping"
features = ["uart"]
priority = 4
start = true
task-slots = [{peer = "pong"}, "usart_driver"]

[tasks.pong]
name = "task-pong"
priority = 3
start = true
task-slots = ["user_leds"]

[tasks.hiffy]
name = "task-hiffy"
priority = 3
features = ["lpc55", "gpio", "spi"]
stacksize = 2048
start = true
task-slots = ["gpio_driver"]

