[package]
name = "task-mgs-responder"
version = "0.1.0"
edition = "2021"

[dependencies]
ringbuf = {path = "../../lib/ringbuf"}
unwrap-lite = {path = "../../lib/unwrap-lite"}
userlib = {path = "../../sys/userlib", features = ["panic-messages"]}
serde = {version = "1", default-features = false, features = ["derive"]}
ssmarshal = {version = "1", default-features = false}
num-traits = {version = "0.2", default-features = false}
task-net-api = {path = "../net-api"}
tinyvec = "1.5.1"

gateway-messages = {path = "../../../omicron/gateway-messages"}

drv-stm32h7-usart = {path = "../../drv/stm32h7-usart", optional = true}

[features]
stm32h743 = ["drv-stm32h7-usart/h743"]
stm32h753 = ["drv-stm32h7-usart/h753"]

# This section is here to discourage RLS/rust-analyzer from doing test builds,
# since test builds don't work for cross compilation.
[[bin]]
name = "task-mgs-responder"
test = false
bench = false
